name = str(input('Por favor, digite seu nome completo: '))
print(name.upper())
print(name.lower())
spliname = name.split()
print(spliname)
joinName = ''.join(spliname)
print(joinName)
print('O nome completo sem os espaços, possui {} caracteres.'.format(len(joinName)))
print('O primeiro nome, possui {} caracteres.'.format(len(spliname[0])))
